micronaut:
  application:
    name: pixKeyManagerGRpc
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5433/keypix`}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
