micronaut:
  application:
    name: pixKeyManagerGRpc
datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/keypix`}
    driverClassName: org.postgresql.Driver
    username: ${POSTGRES_USER:root}
    password: ${POSTGRES_PASSWORD:root}
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true
jpa.default.properties.hibernate.format_sql: true

itau:
  accounts:
    url: 'http://localhost:9091/'